Repository org-roam/org-roam, pull requests merged in 2020-02, with the labels that each got.

#67 Fix org-roam--make-file to create files with extensions
  org-roam.el
Labels: bug

#99 (feature) Add link to backlink line to backlinks buffer
  CHANGELOG.md
  org-roam-utils.el
  org-roam.el
Labels: enhancement, status: in progress

#165 (feature) add org-roam-template
  doc/configuration.md
  org-roam.el
Labels: change, enhancement
