Repository org-roam/org-roam, pull requests merged in 2024-07, with the labels that each got.

#2394 Link Martin Edström's knowledge base
  README.md
Labels: 1. docs

#2441 Update org-roam.org
  doc/org-roam.org
Labels: 1. docs

#2411 Fix Issue #2410 - Unlinked References doesnt work if the org-roam-directory has a space in it.
  org-roam-mode.el
Labels: 2. buffer

#2333 Backlink heading
  CHANGELOG.md
  org-roam-mode.el
Labels: 1. enhancement, 2. buffer
